version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    hostname: influxdb
    ports:
      - 8086:8086
      - 8089:8089/udp
    environment:
      INFLUX_DB: $INFLUX_DB
      INFLUXDB_USER: $INFLUXDB_USER
      INFLUXDB_USER_PASSWORD: $INFLUXDB_USER_PASSWORD
      INFLUXDB_UDP_DATABASE: $INFLUXDB_UDP_DATABASE
      INFLUXDB_UDP_ENABLED: $INFLUXDB_UDP_ENABLED
      INFLUXDB_UDP_BIND_ADDRESS: $INFLUXDB_UDP_BIND_ADDRESS
    volumes:
      - ./influxdb:/var/lib/influxdb

  kapacitor:
    image: kapacitor
    depends_on:
      - influxdb
    container_name: kapacitor
    hostname: kapacitor
    restart: always
    links:
      - influxdb:influxdb
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
    ports:
      - 9092:9092

  telegraf:
    image: telecustom
    depends_on:
      - influxdb
    container_name: telegraf
    hostname: telegraf
    restart: always
    links:
      - influxdb:influxdb
    volumes:
      - ./synology:/var/lib/snmp/mibs
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ./synology:/usr/share/snmp/mibs
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  chronograf:
    image: chronograf:latest
    ports:
      - 8888:8888
    volumes:
      - ./chronograf:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=$INFLUXDB_USER
      - INFLUXDB_PASSWORD=$INFLUXDB_USER_PASSWORD

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 80:3000
    links:
      - influxdb:influxdb
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,\
                          grafana-influxdb-08-datasource,\
                          grafana-kairosdb-datasource,\
                          grafana-piechart-panel,\
                          grafana-simple-json-datasource,\
                          grafana-worldmap-panel,\
                          flant-statusmap-panel"
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    user: "472"

volumes:
  grafana-data:
